### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Nadiroun** [crosswalk-project/crosswalk-samples#24]
Hi all,

I found the idea of this project very interesting, but I keep on having a strange compilation issue. The build of the WebRTC demo always fails with the following error messages : 

BUILD FAILED
/root/Android/Sdk/tools/ant/build.xml:597: The following error occurred while executing this line:
/root/Android/Sdk/tools/ant/build.xml:649: The following error occurred while executing this line:
/root/Android/Sdk/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/tmp/Webrtc-pIn0rj/xwalk_core_library/${aapt}" (in directory "/tmp/Webrtc-pIn0rj/xwalk_core_library"): error=2, Aucun fichier ou dossier de ce type
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:41)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        etc ..

Let me know if you need more information to answer me.

Thanks in advance,

Nadir

**Comment by baleboy** [comment]
Hi, would you mind posting your question to crosswalk-help@lists.crosswalk-project.org? You have a better chance of getting an answer there.

**Comment by Nadiroun** [comment]
Ok, I'll do this. Thank you!
